spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://192.168.100.128:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: itheima
    password: 123321
    host: 192.168.100.128
    publisher-confirm-type: correlated
    publisher-returns: true
  redis:
    host: 192.168.100.128
    database: 1
    port: 6379
    password: xiaoyang
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.100.128/